services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  # Root password is the same as the user password in your case
      - MYSQL_DATABASE=${DB_NAME}           # The name of the database
    volumes:
      - db_data3:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: node_app
    environment:
      - DB_HOST_DEV=localhost
      - DB_HOST_DOCKER=db                  # Database hostname
      - DB_USER=${DB_USER}                  # Database user
      - DB_PASSWORD=${DB_PASSWORD}          # Database user password
      - DB_NAME=${DB_NAME}   
      - DB_PORT=${DB_PORT}               # Database port
      - DATABASE_URL=${DATABASE_URL}   
    command: sh -c "npx prisma migrate deploy &&  npx prisma generate && npm run dev"
      
     
    ports:
      - "3000:3000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data3:
